spring:
  thymeleaf:
  prefix: classpath:/templates/
  suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/myproject
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true # 주석 처리하여 주석 처리된 상태로 둠
        format_sql: true
        default_batch_fetch_size: 30

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace

file:
  dir: /Users/hanjihoon/Desktop/devel/storefile/


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 920925694027-h2q8ah6e7qnqc87o1rm01f81qoisnl50.apps.googleusercontent.com
            client-secret: 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
            scope: # 기본 값 openid,profile,email => profile, email 로 설정 변경
              - profile
              - email

          naver:
            client-id: RV2xAXhsC_cJU3mBpRy5
            client-secret: 91IwwIUSx7
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            #            scope:
            #              - name
            #              - email
            #              - profile_image
            client-name: Naver

          kakao:
            client-id: 314ed193c70a3baf0e7e7d0383680b16
            client-secret: pEfYXXnAaRVSvWLwIm4dmVh1eLPapTHS
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # https://developers.kakao.com/docs/latest/ko/kakaologin/common#user-info
              - profile_nickname
              - profile_image
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-info-authentication-method: header
            user-name-attribute: response # Naver 응답 값 resultCode, message, response 중 response 지정

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-info-authentication-method: header
            user-name-attribute: id # Kakao 응답 값 id, connected_at, properties, kakao_account 중 id 지정
